# Generated by Django 5.1.4 on 2024-12-31 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('imagem_principal', models.ImageField(upload_to='promocoes/')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemPromocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='promocoes/imagens/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('promocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_da_promocao', to='promocoes.promocao')),
            ],
        ),
    ]
