# Generated by Django 5.1.4 on 2025-02-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagempromocao',
            options={'verbose_name': 'Imagem Promoção', 'verbose_name_plural': 'Imagem Promoções'},
        ),
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
    ]
