# Generated by Django 5.1.4 on 2024-12-30 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Título')),
                ('slug_title', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado'), ('priority', 'Prioridade')], default='draft', max_length=12, verbose_name='Status')),
                ('content', models.TextField(verbose_name='Conteúdo da Notícia')),
                ('resume', models.TextField(blank=True, max_length=500, null=True, verbose_name='Resumo da Notícia')),
                ('principal_image', models.ImageField(blank=True, null=True, upload_to='news/images/%Y/%m/%d', verbose_name='Imagem Principal')),
                ('video', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonte da Notícia')),
                ('views', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('share', models.PositiveIntegerField(default=0, verbose_name='Compartilhamentos')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do SEO')),
                ('seo_description', models.TextField(blank=True, max_length=160, null=True, verbose_name='Descrição do SEO')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicar Notícia?')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categorias', models.ManyToManyField(related_name='news', to='categorias.categoria', verbose_name='Escolha as Categorias')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
                'unique_together': {('user', 'news')},
            },
        ),
    ]
