# Generated by Django 5.1.4 on 2025-02-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
    ]
