# Generated by Django 5.1.4 on 2024-12-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('data_inicio', models.CharField(max_length=10)),
                ('data_fim', models.CharField(max_length=10)),
                ('icone_class', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Signo',
                'verbose_name_plural': 'Signos',
                'ordering': ['nome'],
            },
        ),
    ]
