# Generated by Django 5.1.4 on 2024-12-30 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_text', models.CharField(max_length=255)),
                ('votos', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img/enquetes/')),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolha', to='enquetes.enquete')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.enquete')),
                ('escolha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.escolha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'enquete')},
            },
        ),
    ]
