# Generated by Django 5.1.4 on 2024-12-30 20:44

import apps.banners.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to=apps.banners.models.get_banner_upload_path)),
                ('destaque', models.IntegerField(choices=[(1, 'Simples'), (2, 'Destaque'), (3, 'Vip'), (4, 'Capa'), (5, 'Extra')], default='1', verbose_name='Destaque')),
                ('data_inicio', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='banners', to='categorias.categoria')),
                ('fantasia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.empresa', verbose_name='Escolha a Empresa')),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['data_inicio', 'fantasia'],
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_images', models.ImageField(upload_to=apps.banners.models.get_banner_upload_path)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='banners.banner')),
            ],
        ),
        migrations.CreateModel(
            name='BannerView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.banner')),
            ],
        ),
    ]
