# Generated by Django 5.1.4 on 2025-02-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='master_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug_categoria',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug da Categoria'),
        ),
    ]
